// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GoDescargar(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function GoRutaDestino():Promise<string>;
